### PR TITLE
Lemma branch

### PR DESCRIPTION
**Pull request by GezahegnTsegaye**

### CODE REVIEW

**Comment by brunoboss** [comment]
Lemma i cannot accept this pool request, you need to do some other changes:

1) in all the view:  leave only the part that is inside 
       <body>LEAVE ONLY WHAT IS HERE</body>
    without <body>

2) see the professor menu and the use of <c:url  instead of getContext, edit adminMenu and studentMenu so that the link are all matching the same format that in professorMenu

3) in the administratorController you have deleted some code that was previously committed by fabrizio, ensure to not delete or committed work

4) the use of student dashboard is wrong, after looking your code, you have to:

 - use the file commons/menu/menuAdmin or student.jsp  to put all your links to your accessible pages
 - studentDashboard for now, just copy for professor, it will be only an empty page for the moment

Those changes, added to the upper change, should allign your edits with the general structure.

**Comment by brunoboss** [comment]
image

**Comment by brunoboss** [comment]
as you can see on the left i've disposed a menu for the links, and the dashboard (studentHome or professorHome etc) for the moment it's only a page with an <h1>Professor Dashboard</h1>

The page structure (header, footer, menu, content) it's not the official, we will choose one togheter. 
But has all the necessary part to continue the work without focus on user interface. 

As we dediced before the holidays, please use only raw html.  ;-)

**Comment by GezahegnTsegaye** [comment]
ya i see that but using getcontext can help as to pass some values to access another pages

**Comment by brunoboss** [comment]
Ok if you say that getContext() will be usefull, leave it for the moment,  do not forget to add also the logout link copying it from the professor menu.
In the professor menu leave all as is, so we have two working different way to do the things, one in admin and studentMenu and another one in professorMenu.

Please do all the latest requested changing, push and open again another pull request and i will merge if all it's ok

**Comment by brunoboss** [comment]
if you have to import some library (as bootstrap) place it in the files /views/layout/guestLayout.jsp and logged_leftColumnLayout.jsp  and not in every single view. 
If it's possible, please do not use any kind of framework or other things, only raw html. Use the style.css if you need to add some quick style. 

In fact all the styles and so on will be erased after we choose a template. So try to put in the page in the simplest way, don't focus on ui but only in make controllers works well and sending well the things to the view.

**Comment by GezahegnTsegaye** [comment]
ok i understand you now... i will change the getContext some other issues you mentioned but the administrator controller class some code deleted?

**Comment by brunoboss** [comment]
if you go there
https://github.com/asde2016Project2/AcademicManager/pull/46/files
you will find all the edits that you ask for merge

on left there are the old version, on the right there is your version
As you can notice, in the administratorController, there is a initDb function and another one function deleted at the beginning of the file. 
Maybe when you have solved the conflict.

However good job for the moment you are using git in the right way 👍

**Pull request closed without merging**
